version: '2.1'

services:
  gatewayrestredirect:
    image: gatewayrestredirect
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 10000:10000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./dist/main.js